# Generated by Django 4.1.7 on 2025-06-17 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=256)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("email", models.EmailField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
