version: '3'

services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    web:
        build: .
        command: sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        volumes:
            - .:/code
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}

volumes:
    db_data:
