# Generated by Django 4.1.7 on 2023-05-02 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chat_business"),
    ]

    operations = [
        migrations.CreateModel(
            name="WidgetBehavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hide_estimated_wait_time", models.BooleanField(default=False)),
                (
                    "disable_agent_typing_notification",
                    models.BooleanField(default=False),
                ),
                ("disable_sound_notification", models.BooleanField(default=False)),
                ("disable_visitor_typing_function", models.BooleanField(default=False)),
                (
                    "disable_message_preview_on_desktop",
                    models.BooleanField(default=False),
                ),
                (
                    "disable_browser_tab_notification",
                    models.BooleanField(default=False),
                ),
                (
                    "disable_message_preview_on_mobile",
                    models.BooleanField(default=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chat",
            name="identifier",
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
        migrations.CreateModel(
            name="WidgetSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("widget_name", models.CharField(max_length=30)),
                ("widget_status", models.BooleanField(default=False)),
                ("widget_code", models.TextField(blank=True, null=True)),
                ("direct_chat_link", models.URLField(blank=True, null=True)),
                ("widget_color", models.CharField(max_length=30)),
                (
                    "widget_behavior",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior",
                        to="chat.widgetbehavior",
                    ),
                ),
            ],
        ),
    ]
