# Generated by Django 4.1.7 on 2025-06-30 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chat_date_created_chat_is_deleted_chat_last_updated_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="customer_id",
            new_name="id",
        ),
    ]
