# Generated by Django 4.1.7 on 2023-05-03 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_widgetbehavior_chat_identifier_widgetsettings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="phone_nummber",
            new_name="phone_number",
        ),
    ]
