# Generated by Django 4.1.7 on 2025-06-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_rename_customer_id_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INSTAGRAM", "Instagram"),
                    ("FACEBOOK", "Facebook"),
                    ("WHATSAPP", "WhatsApp"),
                    ("TELEGRAM", "Telegram"),
                    ("X", "X (Twitter)"),
                    ("TIKTOK", "TikTok"),
                    ("SHOP", "Shop"),
                ],
                max_length=256,
                null=True,
            ),
        ),
    ]
