# Generated by Django 4.1.7 on 2023-05-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_rename_phone_nummber_customer_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="widgetsettings",
            name="widget_behavior",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="identifier",
        ),
        migrations.AlterField(
            model_name="chat",
            name="agent",
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
        migrations.DeleteModel(
            name="Agent",
        ),
        migrations.DeleteModel(
            name="WidgetBehavior",
        ),
        migrations.DeleteModel(
            name="WidgetSettings",
        ),
    ]
