# Generated by Django 4.1.7 on 2023-05-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_remove_widgetsettings_widget_behavior_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="is_active",
        ),
        migrations.AddField(
            model_name="chat",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "all active chats"),
                    ("resolved", "all resolved chats"),
                ],
                default="active",
                max_length=20,
                null=True,
            ),
        ),
    ]
