# Generated by Django 4.1.7 on 2023-05-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_remove_chat_is_active_chat_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="is_auto_response",
            field=models.BooleanField(default=False),
        ),
    ]
