# Generated by Django 4.1.7 on 2023-05-09 11:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_chat_is_auto_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="chat_session",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
