# Generated by Django 4.1.7 on 2023-05-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_chat_chat_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email address"),
                    ("chat", "Enif Chat Channel"),
                    ("facebook", "Business facebook channel"),
                    ("telegram", "Business Telegram channel"),
                    ("twitter", "Business Twitter channel"),
                ],
                default="chat",
                max_length=20,
                null=True,
            ),
        ),
    ]
