# Generated by Django 4.1.7 on 2023-05-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_chat_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="jarvis_response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
