# Generated by Django 4.1.7 on 2023-05-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_message_sanusi_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="identifier",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
