# Generated by Django 4.1.7 on 2023-05-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_customer_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
