# Generated by Django 4.1.7 on 2023-05-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0012_chat_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="identifier",
            field=models.CharField(blank=True, max_length=72, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=56),
        ),
    ]
