# Generated by Django 4.1.7 on 2023-06-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0013_alter_customer_identifier_alter_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="identifier",
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
