# Generated by Django 4.1.7 on 2023-06-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0014_alter_customer_identifier_alter_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="sentiment",
            field=models.CharField(default="", max_length=52),
        ),
    ]
