# Generated by Django 4.1.7 on 2023-06-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0015_chat_sentiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="escalated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chat",
            name="keyword",
            field=models.CharField(default="", max_length=256),
        ),
    ]
