# Generated by Django 4.1.7 on 2023-08-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0016_chat_escalated_chat_keyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="department",
            field=models.CharField(default="", max_length=256),
        ),
    ]
