# Generated by Django 4.1.7 on 2025-06-17 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_auto_20250617_1150"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailaddress",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="emailaddress",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="user",
            name="uuid",
        ),
        migrations.AddField(
            model_name="emailaddress",
            name="user",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_addresses",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emailaddress",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
