# Generated by Django 4.1.7 on 2025-06-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_remove_emailaddress_user_id_remove_emailaddress_uuid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaddress",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="emailaddress",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailaddress",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
