# Generated by Django 4.1.7 on 2025-06-18 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_emailaddress_date_created_emailaddress_is_deleted_and_more"),
    ]

    # operations = [
    #     migrations.RunSQL(
    #         "ALTER TABLE accounts_user_businesses ALTER COLUMN user_id TYPE uuid USING user_id::uuid;",  # noqa: E501
    #         # reverse_sql="ALTER TABLE accounts_user_businesses ALTER COLUMN user_id TYPE bigint USING user_id::bigint;"  # noqa: E501
    #     ),
    # ]
    operations = [
        migrations.RunSQL(
            """
            TRUNCATE TABLE accounts_user_businesses;
            ALTER TABLE accounts_user_businesses ALTER COLUMN user_id TYPE uuid 
            USING user_id::text::uuid;
            """,
            reverse_sql="ALTER TABLE accounts_user_businesses ALTER COLUMN user_id TYPE bigint;",
        ),
    ]
