# Generated by Django 4.1.7 on 2025-06-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_auto_20250618_1231"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="settings",
            field=models.JSONField(default=dict),
        ),
    ]
