# Generated by Django 4.1.7 on 2025-07-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_invite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modulepermission",
            options={
                "ordering": ["module", "name"],
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["name"],
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.AddField(
            model_name="modulepermission",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="modulepermission",
            name="module",
            field=models.CharField(
                blank=True, help_text="Module this permission belongs to", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="role",
            name="is_system_role",
            field=models.BooleanField(
                default=False, help_text="System roles cannot be deleted"
            ),
        ),
    ]
