# Generated by Django 4.1.7 on 2025-06-17 14:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "message_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("message_content", models.TextField()),
                ("sanusi_response", models.TextField(blank=True, null=True)),
                ("sender_email", models.EmailField(max_length=30)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("chat", "Chat")],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("chat_session", models.JSONField(null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sanusi_messages",
                        to="chat.chat",
                    ),
                ),
            ],
        ),
    ]
