# Generated by Django 4.1.7 on 2025-06-30 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sanusi", "0002_message_date_created_message_is_deleted_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="message_id",
            new_name="id",
        ),
    ]
