"""
Django settings for sanusi_backend project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from decouple import config
import os
from .utils.logging import setup_logging, setup_telemetry

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG")

ALLOWED_HOSTS = [
    # "sanusi-fxotnlz4aa-uc.a.run.app",
    # "dev.sanusi.sanusi.ai",
    # "dev-business.sanusi.ai",
    # "business.sanusi.ai",
    # "sanusi.sanusi.ai",
    "localhost",
    "127.0.0.1",
    "sanusi-t701.onrender.com",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "https://sanusi-t701.onrender.com",
]
CORS_ALLOW_CREDENTIALS = True

# Initialize logging and telemetry
setup_logging()
setup_telemetry()


# Application definition

INSTALLED_APPS = (
    # "django_tenants",  # mandatory, should always be before any django app
    "business",
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.admin",
    # third party libraries
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework.authtoken",
    "rest_framework_simplejwt.token_blacklist",
    # "debug_toolbar",
    "drf_yasg",
    "django_filters",
    "crispy_forms",
    "crispy_bootstrap4",
    "corsheaders",
    "accounts",
    "sanusi",
    "chat",
    "analytics",
    "frontend",
    "leads",
    "business.private.apps.PrivateConfig",
)

# TENANT_APPS = (
#     "django.contrib.contenttypes",
#     "sanusi",
#     "chat",
#     "analytics",
#     "frontend",
#     "leads",
#     "business.private.apps.PrivateConfig",
# )

# INSTALLED_APPS = list(SHARED_APPS) + [
#     app for app in TENANT_APPS if app not in SHARED_APPS
# ]

# TENANT_MODEL = "business.Business"
# TENANT_DOMAIN_MODEL = "business.Domain"

MIDDLEWARE = [
    # "django_tenants.middleware.TenantMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", 
    # "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = "sanusi_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sanusi_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "db.sqlite3",
    # }
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST":  config("DB_HOST"),
        "PORT": config("DB_PORT", cast=int),
        "ATOMIC_REQUESTS": True,
    },
}

# DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)

# DEFAULT_FILE_STORAGE = "django_tenants.storage.TenantFileSystemStorage"

AUTH_USER_MODEL = "accounts.User"

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # "EXCEPTION_HANDLER": "utils.error_handler.custom_exception_handler",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=120),
    "SLIDING_TOKEN_REFRESH_LIFETIME_GRACE_PERIOD": timedelta(days=0),
    "SLIDING_TOKEN_LIFETIME_GRACE_PERIOD": timedelta(days=0),
}

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
OPENAI_KEY = config("OPENAI_KEY")

# crispy templates
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"


# CORS_ALLOWED_ORIGINS = config(
#     "ALLOWED_HOSTS", default="*", cast=lambda v: [s.strip() for s in v.split(",")]
# )
# CORS_ORIGIN_ALLOW_ALL = False
# CORS_ALLOW_CREDENTIALS = True
# CORS_ORIGIN_WHITELIST = [
#     "http://localhost:5174",
#     "https://sanusi.sanusi.ai",
#     # other origins you want to allow
# ]


# Dev only: allow all origins (for Swagger or local frontend)
CORS_ALLOW_ALL_ORIGINS = config("DEBUG", cast=bool, default=False)

API_PREFIX = "/api/v1"


SWAGGER_SETTINGS = {
    "DEFAULT_INFO": "sanusi_backend.urls.swagger_info",  # Customize as needed
    "SCHEMA_URL": "/swagger/",  # Customize the URL path for your Swagger documentation
    "SECURITY_DEFINITIONS": {
        "Token": {"type": "apiKey", "name": "Authorization", "in": "header"}
    },
    "DEFAULT_GENERATOR_CLASS": "drf_yasg.generators.OpenAPISchemaGenerator",
    "DEFAULT_API_URL": config(
        "DEFAULT_API_URL", default="http://127.0.0.1:8000"
    ),  # Set the base API URL with the desired scheme
    # Other settings...
}


# CELERY_BROKER_URL = "redis://localhost:6379"
# CELERY_RESULT_BACKEND = "redis://localhost:6379"

# CELERY_BROKER_URL = "pyamqp://myuser:mypassword@localhost:5672/myvhost"
# CELERY_RESULT_BACKEND = "rpc://"
