# Generated by Django 4.1.7 on 2025-06-13 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="schema_name",
        ),
        migrations.DeleteModel(
            name="Domain",
        ),
    ]
