# Generated by Django 4.1.7 on 2023-05-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="company_id",
            field=models.CharField(blank=True, max_length=572, null=True),
        ),
    ]
