# Generated by Django 4.1.7 on 2023-05-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0002_alter_business_company_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="company_id",
            field=models.CharField(blank=True, max_length=572, null=True, unique=True),
        ),
    ]
