# Generated by Django 4.1.7 on 2023-05-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0003_alter_business_company_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="knowledgebase_id",
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
    ]
