# Generated by Django 4.1.7 on 2025-06-17 12:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0004_auto_20250617_1203"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="product_id",
        ),
        migrations.AddField(
            model_name="inventory",
            name="product",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="business.product",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="escalationdepartment",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="knowledgebase_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscription_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
