# Generated by Django 4.1.7 on 2025-06-19 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0006_business_date_created_business_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="business",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="business.business",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="bundle",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="business",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="business.business",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(default=3, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
