# Generated by Django 4.1.7 on 2023-05-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0006_knowledgebase_is_company_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="email",
        ),
        migrations.AlterField(
            model_name="business",
            name="company_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=572, null=True, unique=True
            ),
        ),
    ]
