# Generated by Django 4.1.7 on 2023-08-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0007_remove_business_email_alter_business_company_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="cleaned_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="business",
            name="token",
            field=models.CharField(default="", max_length=72, null=True),
        ),
    ]
