# Generated by Django 4.1.7 on 2025-06-27 12:05

import business.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chat_date_created_chat_is_deleted_chat_last_updated_and_more"),
        ("business", "0009_auto_20250623_1852"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=20, unique=True)),
                ("delivery_info", models.JSONField()),
                ("payment_summary", models.JSONField()),
                (
                    "delivery_date",
                    models.DateTimeField(
                        default=business.models.get_delivery_date, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CANCELLED", "CANCELLED"),
                            ("PENDING", "PENDING"),
                            ("PROCESSING", "PROCESSING"),
                            ("SHIPPED", "SHIPPED"),
                            ("DELIVERED", "DELIVERED"),
                        ],
                        default="PENDING",
                        max_length=60,
                    ),
                ),
                ("platform", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_business",
                        to="business.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_orders",
                        to="chat.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("meta", models.JSONField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_products",
                        to="business.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "product")},
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_id"], name="business_or_order_i_19a9dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["last_updated"], name="business_or_last_up_3a5c69_idx"
            ),
        ),
    ]
