# Generated by Django 4.1.7 on 2025-06-30 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0010_order_orderproduct_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="business",
            old_name="company_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="knowledgebase",
            old_name="knowledgebase_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="subscription_id",
            new_name="id",
        ),
    ]
