# Generated by Django 4.1.7 on 2025-06-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0011_rename_company_id_business_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
        migrations.AddField(
            model_name="product",
            name="serial_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("business", "serial_number"), name="unique_serial_per_business"
            ),
        ),
    ]
