# Generated by Django 4.1.7 on 2025-07-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0012_remove_product_sku_product_serial_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("ecommerce", "Ecommerce"),
                    ("finance", "Finance"),
                    ("medical", "Medical"),
                    ("saas", "Saas"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=60,
            ),
        ),
    ]
