# Generated by Django 4.1.7 on 2025-07-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0013_product_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="meta",
        ),
        migrations.AddField(
            model_name="order",
            name="meta",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
