# Generated by Django 4.1.7 on 2025-07-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0014_remove_orderproduct_meta_order_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="low_in_stock",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="out_of_stock",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="business",
            name="business_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fashion", "Fashion"),
                    ("skincare", "Skincare"),
                    ("food", "Food"),
                    ("electronics", "Electronics"),
                    ("home", "Home"),
                    ("beauty", "Beauty"),
                    ("kids", "Kids"),
                    ("sports", "Sports"),
                    ("crafts", "Crafts"),
                    ("other", "Other"),
                    ("ecommerce", "Ecommerce"),
                    ("finance", "Finance"),
                    ("medical", "Medical"),
                    ("saas", "Saas"),
                ],
                default="",
                max_length=56,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("fashion", "Fashion"),
                    ("skincare", "Skincare"),
                    ("food", "Food"),
                    ("electronics", "Electronics"),
                    ("home", "Home"),
                    ("beauty", "Beauty"),
                    ("kids", "Kids"),
                    ("sports", "Sports"),
                    ("crafts", "Crafts"),
                    ("other", "Other"),
                    ("ecommerce", "Ecommerce"),
                    ("finance", "Finance"),
                    ("medical", "Medical"),
                    ("saas", "Saas"),
                ],
                db_index=True,
                default="AVAILABLE",
                max_length=60,
            ),
        ),
    ]
