# Generated by Django 4.1.7 on 2025-07-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0015_product_is_active_product_low_in_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="low_in_stock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="out_of_stock",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
