# Generated by Django 4.1.7 on 2025-07-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "business",
            "0016_alter_product_is_active_alter_product_low_in_stock_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expiry_date",
            field=models.DateTimeField(null=True),
        ),
    ]
