# Generated by Django 4.1.7 on 2025-07-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0017_product_expiry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.JSONField(default=dict),
        ),
    ]
