# Generated by Django 4.1.7 on 2025-07-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0018_product_size_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
