# Generated by Django 4.1.7 on 2025-07-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0019_alter_product_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="bundle",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.JSONField(default=list),
        ),
    ]
