# Generated by Django 4.1.7 on 2025-07-18 14:25

from django.db import migrations
from django.db.models import Q

def convert_dict_to_list(apps, schema_editor):
    """Convert existing dict data to list format"""
    Product = apps.get_model('business', 'Product') 
    
    # Get all products that have dict data in bundle, tags, or size fields
    products = Product.objects.all()
    
    for product in products:
        updated = False
        
        # Convert bundle field
        if product.bundle and isinstance(product.bundle, dict):
            # Option 1: Convert to list of keys only (loses quantity info)
            product.bundle = list(product.bundle.keys())
            updated = True
            
        
        # Convert tags field
        if product.tags and isinstance(product.tags, dict):
            # Convert dict to list of keys
            product.tags = list(product.tags.keys())
            updated = True
        
        # Convert size field
        if product.size and isinstance(product.size, dict):
            # Convert dict to list of keys
            product.size = list(product.size.keys())
            updated = True
        
        # Save only if changes were made
        if updated:
            product.save(update_fields=['bundle', 'tags', 'size'])
    
    print(f"Converted {products.count()} products from dict to list format")


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0020_alter_product_bundle_alter_product_size_and_more"),
    ]

    operations = [
        migrations.RunPython(
            convert_dict_to_list,
        ),
    ]
