# Generated by Django 4.1.7 on 2025-07-18 14:38

from django.db import migrations
from django.db.models import Q

def convert_dict_to_list(apps, schema_editor):
    """Convert existing dict data to list format"""
    Product = apps.get_model('business', 'Product')
    
    # Get all products - we need to convert ALL products, not just ones with dict data
    products = Product.objects.all()
    
    for product in products:
        updated = False
        
        # Convert bundle field - handle all cases
        if product.bundle is None:
            product.bundle = []
            updated = True
        elif isinstance(product.bundle, dict):
            # Convert dict to list of keys (loses quantity info)
            product.bundle = list(product.bundle.keys())
            updated = True
        elif not isinstance(product.bundle, list):
            # Handle any other data type
            product.bundle = []
            updated = True
        
        # Convert tags field - handle all cases
        if product.tags is None:
            product.tags = []
            updated = True
        elif isinstance(product.tags, dict):
            # Convert dict to list of keys
            product.tags = list(product.tags.keys())
            updated = True
        elif not isinstance(product.tags, list):
            # Handle any other data type
            product.tags = []
            updated = True
        
        # Convert size field - handle all cases
        if product.size is None:
            product.size = []
            updated = True
        elif isinstance(product.size, dict):
            # Convert dict to list of keys
            product.size = list(product.size.keys())
            updated = True
        elif not isinstance(product.size, list):
            # Handle any other data type
            product.size = []
            updated = True
        
        # Save only if changes were made
        if updated:
            product.save(update_fields=['bundle', 'tags', 'size'])
    
    print(f"Converted {products.count()} products from dict to list format")


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0021_auto_20250718_1425"),
    ]

    operations = [
         migrations.RunPython(
            convert_dict_to_list,
        ),
    ]
