# Generated by Django 4.1.7 on 2025-07-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0022_auto_20250718_1438"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("OUT_OF_STOCK", "Out Of Stock"),
                    ("UNAVAILABLE", "Unavailable"),
                    ("AVAILABLE", "Available"),
                    ("LOW_IN_STOCK", "Low In Stock"),
                ],
                db_index=True,
                default="AVAILABLE",
                max_length=60,
            ),
        ),
    ]
