name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Ruff
        run: ruff check .

      - name: format with Ruff
        run: ruff --fix

      - name: Trigger Render deploy
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK_URL" ]; then
            echo "RENDER_DEPLOY_HOOK_URL secret not set" >&2
            exit 1
          fi
          echo "Triggering Render deploy"
          if ! curl --fail --show-error --location --request POST "$RENDER_DEPLOY_HOOK_URL"; then
            echo "Render deploy failed" >&2
            exit 1
          fi
          echo "Render deploy succeeded"
